### ISSUE TITLE
Update to QT5

### ISSUE THREAD

**Issue by tigexplorer** [Skywalker13/DaisyDuck#8]
Hi,

will it be possible to upgrade DaisyDuck to QT5?

Unfortunately, on ubuntu >=20 QT4 libs no longer provided.

**Comment by Skywalker13** [comment]
Hi,

You are right, I should upgrade everything...

**Comment by Skywalker13** [comment]
I begin the work for supporting Qt5.. there are minor regressions.. but it should not be a problem

**Comment by tigexplorer** [comment]
May I ask you, if progress on this is possible? Or, is help needed?

**Comment by Skywalker13** [comment]
It builds and it seems that it works with Qt5 with the current master branch.
